raj1=input("Enter your 1st friend's Birthday: ")
raj2=input("Enter your 2nd friend's Birthday: ")
raj3=input("Enter your 3rd friend's Birthday: ")
raj4=input("Enter your 4th friend's Birthday: ")
raj5=input("Enter your 5th friend's Birthday: ")
print(f"Your 1st friend's Birthday is on {raj1}")
print(f"Your 2nd friend's Birthday is on {raj2}")
print(f"Your 3rd friend's Birthday is on {raj3}")
print(f"Your 4th friend's Birthday is on {raj4}")
print(f"Your 5th friend's Birthday is on {raj5}")